export const DEFAULT_ACTION = 'app/SignUpContainer/DEFAULT_ACTION';
export default {
  SIGNUP_FORM_CHANGED: 'SIGNUP_FORM_CHANGED',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  SIGN_UP_LOADING: 'SIGN_UP_LOADING',
};
