export const DEFAULT_ACTION = 'app/MainPage/DEFAULT_ACTION';

export default {
  MAIN_PAGE_LOADED: 'MAIN_PAGE_LOADED',
  LOADING_PAGE_SUCCESS: 'LOADING_PAGE_SUCCESS',
  LOADING_PAGE_FAILURE: 'LOADING_PAGE_FAILURE',

  REQUEST_RETREIVE_USERS: 'REQUEST_RETREIVE_USERS',
  USERS_RECEIVED: 'USERS_RECEIVED',
  USERS_NOT_RECEIVED: 'USERS_NOT_RECEIVED',

  SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
  REQUEST_GET_USER: 'REQUEST_GET_USER',
  USER_RECEIVED: 'USER_RECEIVED',
  USER_NOT_RECEIVED: 'USER_NOT_RECEIVED',

  UPDATE_USER_INFO_INPUT_CHANGED: 'UPDATE_USER_INFO_INPUT_CHANGED',
  REQUEST_UPDATE_USER_STATUS: 'REQUEST_UPDATE_USER_STATUS',
  USER_STATUS_DID_UPDATED: 'USER_STATUS_DID_UPDATED',
  USER_STATUS_DIDNOT_UPDATED: 'USER_STATUS_DIDNOT_UPDATED',

  INPUT_MESSAGE_CHANGED: 'INPUT_MESSAGE_CHANGED',
  REQUEST_SEND_MESSAGE: 'REQUEST_SEND_MESSAGE',
};
