export const DEFAULT_ACTION = 'app/MainPage/DEFAULT_ACTION';

export default {
  MAIN_PAGE_LOADED: 'MAIN_PAGE_LOADED',
  LOADING_PAGE_SUCCESS: 'LOADING_PAGE_SUCCESS',
  LOADING_PAGE_FAILURE: 'LOADING_PAGE_FAILURE',
  SIGN_OUT: 'SIGN_OUT',
};
