export const CHANGE_USERNAME = 'boilerplate/Home/CHANGE_USERNAME';

export default {
  LOGIN_FORM_CHANGED: 'LOGIN_FORM_CHANGED',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  CLOSE_MODAL: 'CLOSE_MODAL',
  ON_PAGE_LOADED: 'ON_PAGE_LOADED',
};
